algorithm_name = "bfs_multi"
base_algorithm_name = "bfs"

[sampler]
class = "clrs._src.multi_sol.samplers:BfsMultiSampler"

[algorithm]
callable = "clrs._src.multi_sol.algorithms.bfs.generator:bfs_multi"

[evaluator]
callable = "clrs._src.multi_sol.algorithms.bfs.plugin:evaluate_bfs_multisol_batch"
