algorithm_name = "dfs_multi"
base_algorithm_name = "dfs"

[sampler]
class = "clrs._src.multi_sol.samplers:DfsMultiSampler"

[algorithm]
callable = "clrs._src.multi_sol.algorithms.dfs.generator:dfs_multi"

[evaluator]
callable = "clrs._src.multi_sol.algorithms.dfs.plugin:evaluate_dfs_multisol_batch"
